console.log(alert("Let\'s go"));

// create a function to store the scope of (i) creating an array, and (ii) the values assigned to the array, to facilitate accessing those values so the program can concatenate a string at the end of the function 
// NOTE: this turned out to be unnecessary. the original errors that i was running into was because i used multiple let statements, and you CANNOT declare a variable multiple times.  The fix was to eliminate the the let statements, and just have aboutUser[x] = (reassigning the value)

// Create an array to hold--what was previously--the separate variables name, origin, coder, and months

let aboutUser = ["name", "origin", "coder", "months"] ;

// Populate the array using four var statements that correspond to name, origin, coder, and months

aboutUser[0] = prompt("What\'s your name") ;
console.log(aboutUser[0])

aboutUser[1] = prompt("Hi " + aboutUser[0] + ". Where are you from?") ;
console.log(aboutUser[1])

let continny = confirm(aboutUser[0] + " to continue please press OK.") ;

aboutUser[2] = prompt("What type of coder do you want to be?") ;
console.log(aboutUser[2])

aboutUser[3] = prompt("In how many months do you want to be a " + aboutUser[2] + " by?") ;
console.log(aboutUser[3])

// concatenate a string using the four values stored in the area and display it as a msg in a JavaScript box

let msgtoyou = alert("Keep up the good work " + aboutUser[0] + " from " + aboutUser[1] + ", you will be a " + aboutUser[2] + " in " + aboutUser[3] + " months if you work hard.") ;

// 

if (aboutUser[0] != null) {
    document.getElementById('userName').innerText = aboutUser[0]
}

if (aboutUser[1] != null) {
    document.getElementById('userOrigin').innerText = aboutUser[1]
}
if (aboutUser[2] != null) {
    document.getElementById('userCoder').innerText = aboutUser[2] 
}

/* June 28, 2018 note - Below is the prior iteration of code with separate variables
let name = prompt("What\'s your name");
console.log(name)

let origin = prompt("Hi " + name + ". Where are you from?")
console.log(origin)
let continny = confirm(name + " to continue please press OK.")
let coder = prompt("What type of coder do you want to be?")
console.log(coder)
let months = prompt("In how many months do you want to be a " + coder + " by?")
console.log(months)
let msgtoyou = alert("Keep up the good work " + name + " from " + origin + ", you will be a " + coder + " in " + months + " months IF you work hard.")


if (name != null) {
    document.getElementById('userName').innerText = name 
}
// or document.getElementByID('blue').innerHTML

if (origin != null) {
    document.getElementById('userOrigin').innerText = origin 
}
if (coder != null) {
    document.getElementById('userCoder').innerText = coder 
}*/



// Beginnings of a personal stretch goal #1: Store the data entered by the user in an array
//let spitBack = [name, origin, coder]
// Beginnings of a personal stretch goal #2: A guessing game that the end user tries to guess a random integer between 1 and 10 generated by the computer 
// Code Needed:
// 1. Generate a random integer
// 2. Ask the user for their guess
// 3. If the guess >= 1 && guess <= 10 then proceed
// 3a. If the guess != parameters, pop-up alert & go back to Step 2
// 4. Store guess and return guess alert "You guessed x"
// 5. If guess = random integer, then "Yup! Good job!"
// 5a. If guess != random integer, "Nope, guess again. Your guess is too (high/low).
// >>>>>>> Not sure at all how to let them know the guess is too high or too low
//***end comments from June 27, 2018 ***/
// 
//Initial stab at the above (with prelude confirm box)
//let gameIntro = confirm("Before you go, let\'s play a game. Press OK to begin.")
//     if gameIntro = false then { ;
//         alert("Come on. Don't go. One game. Please") ;
//     }
// let number = prompt("What\'s my favorite integer? To make it easier, it's between 1 and 10.")
//         if number < 1 || number < 10 then {
//             alert("Come on, that's not even a proper guess! Between 1 and 10!")
//         }